# Generated by Django 5.1.7 on 2025-04-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Print_Gurus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.AlterModelTable(
            name='events',
            table=None,
        ),
    ]
