# Generated by Django 5.1.7 on 2025-05-04 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Print_Gurus', '0002_alter_events_options_alter_events_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
