# Generated by Django 5.1.7 on 2025-04-23 16:59

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('Print_Gurus', '0002_alter_aboutpagebackground_background_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomments',
            options={'managed': True, 'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='postcomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Print_Gurus.postcomments'),
        ),
        migrations.AddField(
            model_name='postcomments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=now ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Print_Gurus.blogpost'),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
